print("Welcome to the tip calculator.")
total_bill = float(input("What was the total bill? "))
tip_percentage = float(input("What percentage of tip do you want to give? 10, 12, or 15? "))
split_bill = int(input("How many people to split the bill? "))
tip_percentage_money = total_bill*(tip_percentage/100)
total_bill = round(total_bill+tip_percentage_money,2)
print(f"Your total bill is ${total_bill}")
split_bill = round(total_bill/split_bill, 2)
print(f"Everyone should pay ${split_bill}")